---
on:
  - push

jobs:
  terraform:
    name: terraform
    # env:
      # # mariadb_addr: "mariadb_addr={{username}}:{{password}}@tcp(mariadb:3306)/"
      # mariadb_connection_url: "{{username}}:{{password}}@tcp(mariadb:3306)/"
      # mariadb_username: "root"
      # mariadb_password: "root_password"
      # vault_addr: "http://vault:8200"
      # vault_token: "dev_root_token"
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 1
      matrix:
        config:
          - name: default

    services:
      vault:
        image: vault
        env:
          VAULT_DEV_ROOT_TOKEN_ID: "dev_root_token"
        ports:
          - 8200:8200
      mariadb:
        image: mariadb
        env:
          MARIADB_ROOT_PASSWORD: "root_password"
        ports:
          - 3306:3306

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: terraform init
        uses: robertdebock/terraform-action@1.1.2
        with:
          directory: ./examples/${{ matrix.config.name }}
      - name: terraform validate
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: validate
          directory: ./examples/${{ matrix.config.name }}
      - name: terraform plan
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: plan
          directory: ./examples/${{ matrix.config.name }}
        # env:
          # TF_CLI_ARGS: "-var='mariadb_connection_url={{username}}:{{password}}@tcp(mariadb:3306)/' -var='mariadb_username=root' -var='mariadb_password=root_password' -var='vault_addr=http://vault:8200' -var='vault_token=dev_root_token'"
      - name: debug
        run: |
          resolvectl status || exit 0
          nslookup vault || exit 0
          ping -c 3 vault || exit 0
      - name: terraform apply
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: apply
          directory: ./examples/${{ matrix.config.name }}
        env:
          # TF_CLI_ARGS: "-input=false -auto-approve -var='mariadb_connection_url={{username}}:{{password}}@tcp(mariadb:3306)/' -var='mariadb_username=root' -var='mariadb_password=root_password' -var='vault_addr=http://vault:8200' -var='vault_token=dev_root_token'"
          TF_CLI_ARGS: "-input=false -auto-approve"
      - name: terraform destroy
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: destroy
          directory: ./examples/${{ matrix.config.name }}
        env:
          # TF_CLI_ARGS: "-input=false -auto-approve -var='mariadb_connection_url={{username}}:{{password}}@tcp(mariadb:3306)/' -var='mariadb_username=root' -var='mariadb_password=root_password' -var='vault_addr=http://vault:8200' -var='vault_token=dev_root_token'"
          TF_CLI_ARGS: "-input=false -auto-approve"
        if: ${{ always() }}